[workspace]
members = [
    "mqtt-link",
    "rmqtt",
    "rmqtt-plugins/rmqtt-acl",
    "rmqtt-plugins/rmqtt-web-hook",
    "rmqtt-plugins/rmqtt-auth-http",
    "rmqtt-plugins/rmqtt-cluster-broadcast",
    "rmqtt-plugins/rmqtt-cluster-raft",
    "rmqtt-plugins/rmqtt-counter",
    "rmqtt-plugins/rmqtt-http-api",
    "rmqtt-macros"
]

[patch.crates-io]
rmqtt = { path = "rmqtt" }
rmqtt-macros = { path = "rmqtt-macros" }
rmqtt-acl = { path = "rmqtt-plugins/rmqtt-acl" }
rmqtt-web-hook = { path = "rmqtt-plugins/rmqtt-web-hook" }
rmqtt-auth-http = { path = "rmqtt-plugins/rmqtt-auth-http" }
rmqtt-cluster-broadcast = { path = "rmqtt-plugins/rmqtt-cluster-broadcast" }
rmqtt-cluster-raft = { path = "rmqtt-plugins/rmqtt-cluster-raft" }
rmqtt-counter = { path = "rmqtt-plugins/rmqtt-counter" }
rmqtt-http-api = { path = "rmqtt-plugins/rmqtt-http-api" }
